url: https://sakshishah6.github.io
title: Sakshi's homepage
description: This is my personal portfolio.
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
author:
  name: Sakshi Shah
  email: shahsakshi@hotmail.com
